server:
  port: 9090

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 264847sun
  redis:
    port: 6379
    host: 127.0.0.1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

